### ISSUE TITLE
Used depracated method for RN > 0.47

### ISSUE THREAD

**Issue by VitaliiB1989** [divergent-thinking/react-native-switch-audio-output#3]
HI.
Could you please remove overriding of createJSModules in ReactNativeSwitchAudioOutputPackage.java, because it's not incompatible with RN 47+.

**Comment by Kusumoto** [comment]
Hi.
Thank you for your issue reporting. This issue will be fixed in PR #4 and release in next version

**Comment by Kusumoto** [comment]
release in version 1.0.3
